CSF Plugin command line mode
CloudCompare/CloudCompare pull request #1337
Opened 2020-10-21 15:29 UTC by DavixDevelop

Modified [CSF](https://github.com/DavixDevelop/TerraLidar/tree/master/qCSF) plugin for command-line mode usage

2020-10-22 07:52 UTC, dgirardeau commented on plugins/core/Standard/qCSF/README.md
> +		<td><code>-CSF</code></td>
Would it be possible to add this recap in the qCC/CHANGELOG.md file as well?

2020-10-22 07:54 UTC, dgirardeau commented
Not sure why the CI is complaining... Do you need to fix something?

2020-10-22 08:35 UTC, DavixDevelop commented
> Not sure why the CI is complaining... Do you need to fix something?

I'm looking into it right now. And about the changelog, sure.

2020-10-22 12:43 UTC, dgirardeau reviewed
Please, add something in the CHANGELOG.md file as well ;)

2020-10-22 12:43 UTC, dgirardeau commented on plugins/core/Standard/qCSF/include/qCSFCommands.h
> +			//tmpPoint.x = P->x;
to be removed?

2020-10-22 12:43 UTC, dgirardeau commented on plugins/core/Standard/qCSF/include/qCSFCommands.h
> +		static bool csf_postprocessing = false;
why static?

2020-10-22 12:43 UTC, dgirardeau commented on plugins/core/Standard/qCSF/include/qCSFCommands.h
> +		static bool csf_postprocessing = false;
In any case, in this project we set a upper case letters at the beginning of static variable names, and lower case for the others.

2020-10-22 12:43 UTC, dgirardeau commented on plugins/core/Standard/qCSF/include/qCSFCommands.h
> +		ccMesh* clothMesh = nullptr;
it's a little bit misleading to declare this clothMesh variable here, as well as ExportClothMesh . ExportClothMesh is always false for now, but if it was turned to true, it wouldn't work either (as clothMesh is not managed later).

2020-10-22 12:43 UTC, dgirardeau commented on plugins/core/Standard/qCSF/include/qCSFCommands.h
> +		if (cmd.clouds().size() < 1) {
In this project we go the line for opened brackets ({)

2020-10-22 16:00 UTC, dgirardeau approved these changes
That's good with me!

2020-10-22 16:00 UTC, dgirardeau requested changes
Oops, no, remove the <table> and <tr> from Changelog ;)

2020-10-22 17:19 UTC, dgirardeau commented
Sorry about the misunderstanding: I just wanted you to remove the decorations (not the contents!). The contents are super useful...

2020-10-22 19:46 UTC, dgirardeau approved these changes

2020-10-22 19:46 UTC, merged

2020-10-22 19:46 UTC, dgirardeau commented
Thanks a lot!

2020-11-05 13:01 UTC, ChandrikaMedapati commented
Any Help for -CSF filter from command line. Any Examples to understand more..

2020-11-05 15:30 UTC, DavixDevelop commented
> Any Help for -CSF filter from cloud compare command line syntax. Any Examples to understand more.

You can find more in the changelog, under 2.12

2020-11-05 16:35 UTC, ChandrikaMedapati commented
I've tried the below command with following versions  through command line CloudCompare_v2.11.2,CloudCompare_v2.11.3,CloudCompare_v2.12.
"C:\Program Files\CloudCompare\CloudCompare.exe" -O -GLOBAL_SHIFT AUTO "C:\Users\cm27280\Downloads\file.laz" -CSF -SCENES SLOPE -CLOTH_RESOLUTION 0.5 -CLASS_THRESHOLD 0.5
But no luck :( 
can anyone please help me in this

2020-11-05 19:37 UTC, DavixDevelop commented
> I've tried the below command with following versions  through command line CloudCompare_v2.11.2,CloudCompare_v2.11.3,CloudCompare_v2.12.
> "C:\Program Files\CloudCompare\CloudCompare.exe" -O -GLOBAL_SHIFT AUTO "C:\Users\cm27280\Downloads\file.laz" -CSF -SCENES SLOPE -CLOTH_RESOLUTION 0.5 -CLASS_THRESHOLD 0.5
> But no luck :( 
> can anyone please help me in this
> ![image](https://user-images.githubusercontent.com/38787616/98268909-17924100-1fb3-11eb-9bb9-2fae791a793a.png)
> 

    When you build, did you enable the CSF plugin in cmake? You can test this by opening the built program in checking if the plugin is available under plugins.

2020-11-05 20:21 UTC, dgirardeau commented
And mind that only the 2.12.alpha version support this.

2022-06-01 18:16 UTC, melissaur1039 commented
I keep running into an "Unknown or misplaced command: '-CSF'" error when trying to execute this code that iterates through tiles in a folder, code and error shown in this screenshot:
![image](https://user-images.githubusercontent.com/106698350/171473557-998d3350-7e89-4aeb-8b4e-b621e5eea61c.png)
I know the CSF plugin is enabled because it is useable in the CloudCompare program itself. Any ideas? I am brand new to CloudCompare and its command line mode.

2022-06-02 19:59 UTC, melissaur1039 commented
> Ah that's way too old ;)
> 
> You should try with the latest 2.12 version.

Hey, that worked! Thanks for your help. The school isn't great at keeping all of these programs updated :(

2023-07-28 16:06 UTC, samchris3211 commented
Hi , i've tried running this in python
subprocess.call(["D:/CloudCompare_v2.12.4_bin_x64/CloudCompare.exe","-AUTO_SAVE","OFF","-C_EXPORT_FMT",file0,"-o", output_file,"-CSF","-SCENES SLOPE","-CLOTH_RESOLUTION","0.5","-CLASS_THRESHOLD","0.5"])

it works fine, however I need to know where the output file is as I can't find it?
The process executes but I just needs it output.

2023-08-01 09:17 UTC, dgirardeau commented
Can you maybe use '-SAVE_CLOUDS' or '-SAVE_MESHES' to force the saving of the files?