Typo docs
CloudCompare/CloudCompare pull request #1495
Opened 2021-08-08 20:32 UTC by tmontaigu

Fix a bunch of typos in comments/documentation.

And use \warning for better doxygen output.

There are some typos in methods names, should we also correct them ?

2021-08-09 15:08 UTC, dgirardeau commented
Yes, don't hesitate!

2021-08-09 15:08 UTC, dgirardeau approved these changes

2021-08-09 20:02 UTC, dgirardeau approved these changes

2021-08-09 20:03 UTC, dgirardeau requested changes
It seems something is broken?

2021-08-09 20:34 UTC, tmontaigu commented
Yes, on my local build I do not build a lot of plugins, so some renamed function were missed by the refactoring tool

2021-08-12 19:20 UTC, dgirardeau requested changes

2021-08-12 19:20 UTC, dgirardeau commented on libs/CCPluginAPI/include/ccOverlayDialog.h
> +	void addoverriddenShortcut(Qt::Key key);
Why removing the capital 'O'?

2021-08-12 19:20 UTC, dgirardeau commented on libs/qCC_db/include/ccDrawableObject.h
> +	inline virtual void enableTempColor(bool state) {
Not sure about the way to format this

2021-08-12 19:20 UTC, dgirardeau commented on libs/qCC_db/src/ccDrawableObject.cpp
> +	,
should be on one line

2021-08-12 19:20 UTC, dgirardeau commented on libs/qCC_db/src/ccHObject.cpp
> +			QString classId = child->getMetaData(
should be on one line (both)

2021-08-12 19:20 UTC, dgirardeau commented on libs/qCC_glWindow/include/ccGLWindow.h
> +	bool hasoverriddenDisplayParameters() const { return m_overriddenDisplayParametersEnabled; }
capital O

2021-08-12 19:20 UTC, dgirardeau commented on libs/qCC_glWindow/src/ccGLWindow.cpp
> +		setDisplayParameters(params, hasoverriddenDisplayParameters());
capital O

2021-08-12 19:20 UTC, dgirardeau commented on libs/qCC_glWindow/src/ccGLWindow.cpp
> +				setDisplayParameters(params,hasoverriddenDisplayParameters());
same

2021-08-13 08:55 UTC, tmontaigu commented on libs/CCPluginAPI/include/ccOverlayDialog.h
> +	void addoverriddenShortcut(Qt::Key key);
It was a mistake

2021-08-17 18:18 UTC, dgirardeau requested changes

2021-08-17 18:18 UTC, dgirardeau commented on qCC/extern/QCustomPlot/qcustomplot.cpp
> +  // don't setRenderHint(QPainter::NonCosmeticdefaultPen) here, because painter isn't active yet and
Shouldn't it be NonCosmeticDefaultPen? I guess it doesn't compile?

2021-08-17 18:19 UTC, dgirardeau commented on qCC/extern/QCustomPlot/qcustomplot.cpp
> +  // don't setRenderHint(QPainter::NonCosmeticdefaultPen) here, because painter isn't active yet and
Ah sorry, it's a comment :D

2021-08-22 14:42 UTC, dgirardeau approved these changes

2021-08-22 14:42 UTC, merged

2021-08-22 14:42 UTC, dgirardeau commented
Once again, thanks for your work!

2021-08-22 20:22 UTC, tmontaigu commented
Thanks for the reviews