SF tools: Split cloud using SF / Set classification field
CloudCompare/CloudCompare pull request #1609
Opened 2022-03-07 12:52 UTC by p-leroy

Two tools added to the "Edit" menu:
- Edit / Scalar fields / Split cloud using SF => split a cloud using the current scalar field
- Edit / Scalar fields / Set classification field => set the "Classification" field of the selected clouds (create the field if needed)

One option added to the "Segment" tool: 
The button "CLASS" enables to set the class of the current selection (the field "Classification" is created if needed).

2022-03-07 16:41 UTC, dgirardeau requested changes

2022-03-07 16:41 UTC, dgirardeau commented on qCC/ccSetClassificationField.cpp
> +int ccSetClassificationField::getClass()
method should be const

2022-03-07 16:41 UTC, dgirardeau commented on qCC/ccSetClassificationField.h
> +//namespace ccHObject{
to be removed?

2022-03-07 16:41 UTC, dgirardeau commented on qCC/ccSetClassificationField.h
> +    ~ccSetClassificationField();
~ccSetClassificationField() override;

2022-03-07 16:41 UTC, dgirardeau commented on qCC/ccSetClassificationField.h
> +    Ui::ccSetClassificationField *ui;
m_ui

2022-03-07 16:41 UTC, dgirardeau commented on qCC/ccSetClassificationField.h
> +    int class_;
m_class

2022-03-07 16:41 UTC, dgirardeau commented on qCC/ccSetClassificationField.h
> +class ccSetClassificationField : public QDialog
It would be good to add Dlg or Dialog at the end --> ccSetClassificationFieldDialog

2022-03-07 16:41 UTC, dgirardeau commented on qCC/db_tree/ccDBRoot.cpp
> +    else
you can remove the 2 next lines (else ... return;}

2022-03-08 08:05 UTC, p-leroy commented on qCC/ccEntityAction.cpp
> +                    app->addToDB(pc); // add to data base
I have removed the group, taking into account a previous remark

2022-03-08 08:46 UTC, p-leroy commented on qCC/ccGraphicalSegmentationTool.cpp
> +    // the following lines are very similar to the segment tool
I did not want to modify your code by security, but yes, some mutualization should be possible. Maybe for a future PR?

2022-03-08 20:37 UTC, dgirardeau approved these changes

2022-03-09 19:14 UTC, merged