Add support for comments inside a command file
CloudCompare/CloudCompare pull request #1930
Opened 2024-01-03 12:09 UTC by HeadLessHUN

syntax:
```
# whole line comment
// whole line comment
-SS OCTREE 10 //subsample cloud with octree level 10
 # this will run octree 10 rename_entities is commented out then save 
-SS OCTREE 10 '/* -RENAME_ENTITIES "rename" */' -SAVE_CLOUDS #we can use hashtags here as well
```

2024-01-03 20:56 UTC, dgirardeau requested changes

2024-01-03 20:56 UTC, dgirardeau commented on qCC/ccCommandLineCommands.cpp
> +					QString commentStr = "[COMMENT] ";
I wouldn't initialize this string each time, as creating a QString object is quite expensive... Let me change this and you'll tell me if it's ok with you.

2024-01-03 21:40 UTC, dgirardeau commented
Tell me what you think about the new version

2024-01-03 22:42 UTC, HeadLessHUN commented
if we are concerned about this then, we could do early aborts on lines, and breaking out from the loop as soon as we got a line comment identifier. But in that case we won't be able to print them out at least in place. if you want i could prepare a version for this.

2024-01-04 07:31 UTC, dgirardeau commented
Ok I'll let you test first.

I was indeed surprised that a 'full line' comment (which can actually be a partial line comment, as it can appear in the middle of the line - but that's ok, apart for the name) would still be processed in multiple chunks. I guess the chunks could be re-merged at this point, and displayed in one go (with the 'join' method of QStringList?). And then the loop can be ended earlier indeed. That's maybe the only change worthy of an effort.

2024-01-04 12:17 UTC, dgirardeau approved these changes

2024-01-04 16:31 UTC, merged