Verbosity level and other related changes
CloudCompare/CloudCompare pull request #1956
Opened 2024-02-06 12:09 UTC by HeadLessHUN

#1949

2024-02-07 17:35 UTC, dgirardeau requested changes

2024-02-07 17:35 UTC, dgirardeau commented on qCC/ccCommandLineCommands.cpp
> +		cmd.print(QObject::tr("Set verbosity level to %i").arg(verbosityLevel));
```suggestion
		cmd.print(QObject::tr("Set verbosity level to %1").arg(verbosityLevel));
```

2024-02-07 17:35 UTC, dgirardeau commented on qCC/ccCommandLineCommands.cpp
> -			{
to be restored

2024-02-07 17:35 UTC, dgirardeau commented on qCC/ccCommandLineCommands.cpp
> +		return cmd.error(QObject::tr("Missing parameter: verbosity level after: %s").arg(COMMAND_VERBOSITY));
```suggestion
		return cmd.error(QObject::tr("Missing parameter: verbosity level after: %1").arg(COMMAND_VERBOSITY));
```

2024-02-07 17:35 UTC, dgirardeau commented on qCC/ccCommandLineCommands.cpp
> +	if (!ok) {
```suggestion
	if (!ok)
	{
```

2024-02-07 17:35 UTC, dgirardeau commented on qCC/ccCommandLineCommands.cpp
> +		return cmd.error(QObject::tr("Invalid verbosity level %s").arg(verbosityLevel));
```suggestion
		return cmd.error(QObject::tr("Invalid verbosity level %1").arg(verbosityLevel));
```

2024-02-07 17:35 UTC, dgirardeau commented on qCC/main.cpp
> +		if (argumentsLocal8Bit[lastArgumentIndex].toUpper() == "-VERBOSITY")
I guess you should check that 'lastArgumentIndex < argumentsLocal8Bit.size()' first?

2024-02-07 17:35 UTC, dgirardeau commented on qCC/main.cpp
> +				ccLog::Error(QObject::tr("Invalid verbosity level %s").arg(verbosityLevel));
```suggestion
				ccLog::Error(QObject::tr("Invalid verbosity level %1").arg(verbosityLevel));
```

2024-02-07 20:06 UTC, HeadLessHUN commented
Daniel, i wanted to have higher level for command name print/subprocess time. That is why i used warning, maybe we should/could add a new level instead?:)

2024-02-07 20:14 UTC, dgirardeau commented
Yes I realized that. I think we need to add more levels indeed.

Warning and Errors can't be 'ignored' (at least not errors). And they have to be reserved for real warnings and errors.

I think we will have to work a little bit more on that, and sadly we might not be able to add that to the release...

2024-02-07 20:26 UTC, HeadLessHUN commented
I was thinking about flipping debug and print as well, and allow debug in release mode as well, just make the standard as default.

Maybe we could add a higher lvl print. and that should be enough?

2024-02-07 20:28 UTC, dgirardeau commented
Yes, Debug could become the 'verbose' mode, disabled by default (unless you are in Debug mode).

What was your intent by putting the timing logs as 'warning'? Do you think they are more important than standard messages? Or on the contrary part of the verbose/debug logs?

2024-02-07 20:31 UTC, HeadLessHUN commented
well i wanted to have a start/end of a command so that should be higher level i think, At least for me these are more important, then messages inside commands.

2024-02-07 20:33 UTC, dgirardeau commented
Ok, so something like that?
Debug = 0 (=Verbose)
Print = 1
Important/High = 2
Warning = 3
Error = 4

2024-02-07 20:37 UTC, HeadLessHUN commented
for me that looks fine :) I don't really know if we want to mess with gui mode logs or not... I usually never look the console log in gui mode. So i wouldn't bother. But maybe if we are implementing this, it worth a select menu inside the preferences menu.

2024-02-07 20:38 UTC, dgirardeau commented
Yes, for now it's ok to only give this option to the command line users (as in the GUI mode, you can simply hide the console).

I'll try something quick so as to ship that with the release.

2024-02-07 22:22 UTC, dgirardeau commented
Ok, here's the new version:
![image](https://github.com/CloudCompare/CloudCompare/assets/2735509/1a75189c-b1f7-4d9a-90c7-13ca29886b98)

I've tested it quickly. You can try it on your side. And we should be good to add it to the release!

2024-02-08 07:15 UTC, HeadLessHUN commented on qCC/ccCommandLineParser.h
> +	void printVerbpse(const QString& message) const override;
typoo here too

2024-02-08 07:15 UTC, HeadLessHUN commented on libs/CCPluginAPI/include/ccCommandLineInterface.h
> +	virtual void printVerbpse(const QString& message) const = 0;
typoo
printVerbose

2024-02-08 07:33 UTC, dgirardeau commented on qCC/ccCommandLineParser.h
> +	void printVerbpse(const QString& message) const override;
Wow, I was tired 😫

2024-02-08 07:55 UTC, HeadLessHUN commented
currently i have build error, but i'm sure it just my environment went wrong somewhere. but i was not able to test these changes yet.

2024-02-08 07:59 UTC, dgirardeau commented
Ah ok, keep me updated!

2024-02-08 08:24 UTC, HeadLessHUN commented
> Ah ok, keep me updated!

well something is really f*cked up :) my env however is clean and reset to the verbosity_level branch, but they contain changes from the master branch which you pushed yesterday. So there are missing files. bcadd49365e51e75836529fee64c5253e3e6932c

2024-02-08 09:09 UTC, dgirardeau commented
Ok I need to merge some stuff in the PythonPlugin first.

2024-02-08 18:05 UTC, merged

2024-02-21 09:55 UTC, ryukisai commented
Thanks for this guys! I had not realized it was already implemented.