add_qVoxFall_plugin
CloudCompare/CloudCompare pull request #2059
Opened 2024-09-19 12:14 UTC by farmakis

We would like to contribute a plugin created by our research group at  the univrsity of Newcastle, NSW, Australia as part of an open pit mine monitoring program.
It concerns rockfall detection and volume estimation between two 3D models using a voxel grid.

2024-09-21 08:55 UTC, dgirardeau requested changes
Thanks very much for the contribution!

Apart for a few syntax comments, my main comment would be that we prefer now to keep the code of these plugins in their original repository (so that you keep the ownership of the code), and we simply point to it as a submodule. Can you reorganize the files so that the root of the repository is the qVoxFall folder? You can create a new repository to not overwrite everything in the existing one.

See how it's done with the MPlane plugin for instance: https://github.com/hvs-ait/mplane-plugin/ (we then add the repository as a submodule in plugins/core

2024-09-21 08:55 UTC, dgirardeau commented on plugins/private/qVoxFall/include/qVoxFallDialog.h
> +//#                             COPYRIGHT: XXX                             #
Missing copyright

2024-09-21 08:55 UTC, dgirardeau commented on plugins/private/qVoxFall/include/qVoxFall.h
> +#ifndef Q_VOXFALL_PLUGIN_HEADER
Wherever there's a _#pragma once_ statement, you don't need the _#ifnded Q_XXX + #define Q_XXX + #endif_ statements (I think it applies to pretty much all header files?)

2024-09-21 08:55 UTC, dgirardeau commented on plugins/private/qVoxFall/src/qVoxFall.cpp
> +
a lot of spurious blank lines?

2024-09-21 08:55 UTC, dgirardeau commented on plugins/private/qVoxFall/src/qVoxFallDialog.cpp
> +
spurious blank lines

2024-09-21 08:57 UTC, dgirardeau commented
Also, do you have any documentation we can point to in the wiki? Or do you want to create the wiki page directly maybe? (in which case I can create an account for you to edit it)

2024-09-21 12:25 UTC, farmakis commented
Thank you for the review.

We have created the repository as requested, including the suggested changes in the files.

As for the documentation, there is a relevant research article that has just gone through the review phase. Soon to be published.

2024-09-22 05:33 UTC, dgirardeau commented
> Thank you for the review.
> 
> We have created the repository as requested, including the suggested changes in the files.
> 
> As for the documentation, there is a relevant research article that has just gone through the review phase. Soon to be published.

Thanks. What's the address of this new repository?

2024-09-22 06:41 UTC, farmakis commented
> > Thank you for the review.
> > We have created the repository as requested, including the suggested changes in the files.
> > As for the documentation, there is a relevant research article that has just gone through the review phase. Soon to be published.
> 
> Thanks. What's the address of this new repository?

Here is the link to the repository:
https://github.com/farmakis/qVoxFall

2024-09-22 07:54 UTC, dgirardeau commented
Thanks. Would you agree to give me some access rights to this repo so that I can push minor fixes? (and later it might come handy to do some maintenance work).

2024-09-22 08:05 UTC, farmakis commented
> Thanks. Would you agree to give me some access rights to this repo so that I can push minor fixes? (and later it might come handy to do some maintenance work).

Absolutely. Thanks

2024-09-22 08:05 UTC, dgirardeau commented
Thanks. Here's the PR: https://github.com/farmakis/qVoxFall/pull/1

2024-09-22 08:20 UTC, dgirardeau commented
Here's the actual integration PR (as a submodule): https://github.com/CloudCompare/CloudCompare/pull/2061

2024-09-22 08:21 UTC, dgirardeau commented
I'll close this one, but it's still interesting to look at the compilation issues on Linux and macOS

2024-09-22 08:21 UTC, closed without merging

2024-09-22 10:33 UTC, farmakis commented
> I'll close this one, but it's still interesting to look at the compilation issues on Linux and macOS

Yes, I do not really see what causes those compilation issues. We 'll have a look again.
We would also need to update the disclaimer text when the relevant article is released.

2025-02-26 08:37 UTC, farmakis commented
Dear CC team,

Regarding the documentation for the qVoxFall plugin.
The paper is about to be published the following days. Could you please give me access to edit a corresponding wiki page where I can also point to the publication?

Thank you,

---------------------------------------------------
Dr. Ioannis Farmakis, Ph.D.
Postdoctoral Researcher
Sapienza Università di Roma
Email: ***@***.*** 

> On 22 Sep 2024, at 7:33 AM, Daniel Girardeau-Montaut ***@***.***> wrote:
> 
> 
> Thank you for the review.
> 
> We have created the repository as requested, including the suggested changes in the files.
> 
> As for the documentation, there is a relevant research article that has just gone through the review phase. Soon to be published.
> 
> Thanks. What's the address of this new repository?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/CloudCompare/CloudCompare/pull/2059#issuecomment-2365478841>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQCXD744Z72ZMDOFHUPFGXDZXZJDXAVCNFSM6AAAAABOPZA5OOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRVGQ3TQOBUGE>.
> You are receiving this because you authored the thread.
>

2025-03-03 07:18 UTC, dgirardeau commented
@farmakis  Can you send a mail to admin@cloudcompare.org about that so that I can send you a wiki account?